@extends('front.layouts.master')

@section('seo_title', $global_other_page_items->page_terms_seo_title)
@section('seo_meta_description', $global_other_page_items->page_terms_seo_meta_description)

@section('content')
<!-- Start main-content -->
        <section class="about-section"  style="background-image: url({{ asset('uploads/'.$global_setting->banner) }});"> 
		<div class="container">
			<div class="row about-breadcrumbs">
				<div class="col-md-6">
					<div class="about-head">
						<h2>Terms and Conditions</h2>
					</div>
				</div>
				<div class="col-md-6">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumbs">
							<li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('Home') }}</a></li>
							<li class="breadcrumb-item active" aria-current="page">Terms and Conditions</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
	</section>
<!-- end main-content -->

 <div class="leading-page py-4">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="leading-content">
						<div class="head-title">
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">JustPing.com Terms and Conditions for Vendors</h2>
							<p class="m-top-30 text-black aos-init aos-animate" data-aos="fade-up" data-aos-delay="400">This document is an electronic record in terms of the amended Information Technology Act,
2000 and rules and regulation made thereunder. This electronic record is generated by a
computer system and does not require any physical or digital signatures. This document is
published in accordance with the provisions of Rule 3 (1) of the Information Technology
(Intermediaries Guidelines) Rules, 2011. This document meets the stipulations and
conditions mentioned in Section 65B (2) of the Indian Evidence Act, 1872.</p>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init aos-animate">These Terms of Service govern the contractual relationship between Vendors (hereinafter
referred to as "Vendor," "Service Provider," "You," or "Your") and JustPing.com (hereinafter
referred to as "JustPing.com," "We," "Us," or "Our"), and it governs the services offered by
JustPing.com through its website (www.justping.com), phone, SMS, WAP, app, or any other
medium (collectively called "Platforms"). JustPing.com offers its services to you only on
these Terms and any amendments made under these Terms of Service. JustPing.com will
endeavor to make these Terms of Service available to you via your registered email ID
and/or mobile number via email/SMS/WhatsApp and the same is also published on
JustPing.com’s website at [Link to Terms Page].
</p>
										
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">1. Introduction:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">The Services (defined hereinafter) of JustPing.com are provided by [JustPing.com's Legal
Entity Name and Address]. JustPing.com provides information about Vendors (defined
hereinafter) of various products and services ("Information") in selected areas ("Service") to
end-users. JustPing.com is a platform that connects the general public with Vendors' goods
and services listed on JustPing.com, but does not guarantee any business to such Vendors.
Vendor details as provided by them are specified in the listing available on JustPing.com’s
Platforms. JustPing.com’s objective is to provide a user-friendly guide for up-to-date
Information. End-users ("Users") of the Service are persons who may want to purchase
goods/avail services and are seeking information about the Vendors of such goods and
services. These Terms of Service and the invoice (if applicable) constitute the entire
understanding/contract between JustPing.com and the Vendors.</p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">2. Interpretation:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(a) "Contract" means these Terms of Service together with all schedules and annexures (if
any). (b) References to a party hereunder shall include such party’s successors, permitted
assigns, and any persons deriving title under it. (c) The descriptive headings of clauses are
for convenience only and are not intended as complete descriptions of the content. (d) The
use of words in the singular or plural, or with a particular gender, shall not limit the scope or
exclude the application of any provision unless the context otherwise permits. (e) Any
grammatical form of a defined term herein shall have the same meaning as that of such
term. (f) The words "including" and "includes" herein shall always mean "including, without
limitation" and "includes, without limitation," respectively.
 </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">3. Subscription:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">Vendors may be business houses, small and medium enterprises, corporate entities,
semi-corporate entities, establishments, or individuals who subscribe to the Service to list
their company or business. JustPing.com will provide only the Information about the Vendor
to the Users. Vendor agrees and acknowledges that JustPing.com does not guarantee any
business to the Vendor and is merely a medium through which information is made available
to the public.
 </p>
							
								<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">4. General Terms:</h2>
							<ul>
								<li>(i) These Terms of Service, including any invoice, annexures, etc., will be referred to as the
"Contract/Terms of Service." These Terms of Service will override any previous
understanding (whether written or oral) between the Vendor and JustPing.com. The Terms of
Service shall be valid and effective for a specified period (e.g., one year) from the effective
date unless otherwise agreed by the parties. Renewal terms will be specified separately.</li>
								<li>(ii) The automatic renewal of the Service, if applicable, is subject to the absolute discretion of
JustPing.com and may be subject to revised terms and pricing.</li>
								<li>(iii) The Vendor authorizes JustPing.com to share the Vendor’s details and contact numbers
for business and promotional purposes with Users of the Service and for other business
purposes of JustPing.com, irrespective of the Vendor's registration in any "Do Not Call"
registry.</li>
								<li>(iv) The Vendor confirms that they shall carry out all the obligations specified in the Terms of
Service and undertake to take all necessary measures to ensure that Users do not
encounter any difficulty in contacting the Vendor.</li>
							</ul>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init"><bold>Add other relevant general terms from the Just Dial document, adapting them to
JustPing.com's services and business model. Be sure to address payment terms,
consequences of non-payment, intellectual property rights, user-generated content,
disclaimers, limitations of liability, indemnification, confidentiality, governing law,
								dispute resolution, and any other relevant provisions.)</bold>
 </p>
							
								<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">5. Information Dissemination:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">JustPing.com disseminates Information to Users through various Platforms. JustPing.com
may, at its discretion, cease providing Information over any of the above Platforms or provide
Information over other Platforms or modify the manner in which Information is provided.
 </p>
							
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">6. Vendor Listings:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Describe the different listing options available to Vendors on JustPing.com, including any
premium listings, packages, or other options. Clearly define the features and costs
associated with each option. Address how listings are prioritized and displayed.)
 </p>
							<p><bold>(Adapt the listing details from the Just Dial document to reflect JustPing.com's
specific offerings.)</bold></p>
							
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">7. "JustPing Verified" Stamp (If Applicable):</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Describe the verification process and what the "JustPing Verified" stamp signifies.)
 </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">8. "JustPing Trusted" Stamp (If Applicable):</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Describe the "JustPing Trusted" stamp and its criteria.)
 </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">9. Listing Service and Other Fees:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Detail the fee structure for listing services and any other applicable charges. Specify
payment methods and terms.)
 </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">10. Payment Modes:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(List the acceptable payment methods.) </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">11. Consequences of Non-Payment:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Outline the consequences of failing to pay fees, including suspension or termination of
services.)</p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">12. Lump Sum Payment Mode (If Applicable):</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Describe any lump sum payment options and associated benefits.) </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">13. Issuance of Invoice/Annexures:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Explain the invoice process.)</p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">14. Priority of Information about Vendors:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Describe how Vendor information is prioritized and displayed to Users.) </p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">15. No Guarantee of Business:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(State clearly that JustPing.com does not guarantee business for Vendors.)</p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">16. No Marketing:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Clarify that JustPing.com is not obligated to market the Vendor's offerings.)</p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">17. Indemnification:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Include an indemnification clause similar to the Just Dial example, adapted for
JustPing.com.)</p>
							<h2 class="nusys-title aos-init aos-animate" data-aos="fade-up">18. Confidentiality and Related Obligations:</h2>
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init">(Include a confidentiality clause regarding User Information.)</p>
							
							<p data-aos="fade-up" data-aos-delay="400" class="aos-init"><bold>(Continue adding and adapting clauses from the Just Dial document as necessary,
always ensuring they are relevant to JustPing.com's services and legally sound.

Consult with legal counsel to ensure your Terms and Conditions are comprehensive
and compliant with all applicable laws and regulations.)<bold></p>
							

							<div class="separator-left"></div>
						</div>
					</div>
				</div>
				<!-- <div class="col-md-5">
					<div class="leading-img0">
						<img src="assets/img/about1.png" alt="slider" class="img-fluid" data-aos="fade-left">
					</div>
				</div> -->
			</div>
   
		</div>
        
	</div>
<!--<section class="blog-details">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {!! clean($global_other_page_items->page_terms_content) !!}
            </div>
        </div>
    </div>
</section>-->
@endsection